# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Practice_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 363)
        MainWindow.setStyleSheet("background-color:rgb(98,98,98)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 73))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 73))
        font = QtGui.QFont()
        font.setFamily("楷体")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 5)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout.addWidget(self.widget_5, 0, 6, 4, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(75, 44))
        self.label.setMaximumSize(QtCore.QSize(75, 44))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255);\n"
"border:2px solid rgb(255,255,255);\n"
"font-size:14pt")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 3, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setMinimumSize(QtCore.QSize(75, 52))
        self.statusLabel.setMaximumSize(QtCore.QSize(75, 52))
        self.statusLabel.setStyleSheet("color:rgb(255, 255, 255);\n"
"font-size:20")
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 1, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 4, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 131))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 131))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 3, 1, 1, 1)
        self.start_confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_confirm_button.setMaximumSize(QtCore.QSize(75, 23))
        self.start_confirm_button.setStyleSheet("color:rgb(255,255,255)")
        self.start_confirm_button.setObjectName("start_confirm_button")
        self.gridLayout.addWidget(self.start_confirm_button, 3, 3, 1, 1)
        self.trueButton = QtWidgets.QPushButton(self.centralwidget)
        self.trueButton.setMinimumSize(QtCore.QSize(131, 131))
        self.trueButton.setStyleSheet("color:rgb(85, 255, 0)")
        self.trueButton.setObjectName("trueButton")
        self.gridLayout.addWidget(self.trueButton, 3, 2, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setStyleSheet("color:rgb(255,255,255)")
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 3, 5, 1, 1)
        self.FalseButton = QtWidgets.QPushButton(self.centralwidget)
        self.FalseButton.setMinimumSize(QtCore.QSize(121, 131))
        self.FalseButton.setStyleSheet("color:rgb(255, 12, 12)")
        self.FalseButton.setObjectName("FalseButton")
        self.gridLayout.addWidget(self.FalseButton, 3, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; color:#ffffff;\">您已经成功完成练习模块。在主测试中，您将看到一串非汉字的遮挡性字符串，分别在中文词汇的先后持续展200 ms左右。</span></p></body></html>"))
        self.start_confirm_button.setText(_translate("MainWindow", "开始"))
        self.trueButton.setText(_translate("MainWindow", "Y 正确"))
        self.exitButton.setText(_translate("MainWindow", "退出测试"))
        self.FalseButton.setText(_translate("MainWindow", "N 错误"))
