# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 353)
        MainWindow.setStyleSheet("background-color:rgb(98,98,98)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 0, 1, 7)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout.addWidget(self.widget_5, 1, 6, 4, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 1, 0, 4, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(400, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 197))
        font = QtGui.QFont()
        font.setFamily("楷体")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 1, 1, 5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 132))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255);\n"
"border:2px solid rgb(255,255,255);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 5)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setStyleSheet("color:rgb(255,255,255)")
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 4, 5, 1, 1)
        self.FalseButton = QtWidgets.QPushButton(self.centralwidget)
        self.FalseButton.setStyleSheet("color:rgb(255,255,255)")
        self.FalseButton.setObjectName("FalseButton")
        self.gridLayout.addWidget(self.FalseButton, 4, 4, 1, 1)
        self.trueButton = QtWidgets.QPushButton(self.centralwidget)
        self.trueButton.setStyleSheet("color:rgb(255,255,255)")
        self.trueButton.setObjectName("trueButton")
        self.gridLayout.addWidget(self.trueButton, 4, 2, 1, 1)
        self.start_confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_confirm_button.setStyleSheet("color:rgb(255,255,255)")
        self.start_confirm_button.setObjectName("start_confirm_button")
        self.gridLayout.addWidget(self.start_confirm_button, 4, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; color:#ffffff;\">现在是练习模式。在练习模式中，您将先后看到两个中文词汇，请判断二者是否相同。点击“开始”进入第一组测试。</span></p></body></html>"))
        self.exitButton.setText(_translate("MainWindow", "退出练习模式"))
        self.FalseButton.setText(_translate("MainWindow", "F"))
        self.trueButton.setText(_translate("MainWindow", "T"))
        self.start_confirm_button.setText(_translate("MainWindow", "开始"))
