# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(98,98,98)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(130, 50, 581, 81))
        font = QtGui.QFont()
        font.setFamily("楷体")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.start_confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_confirm_button.setGeometry(QtCore.QRect(370, 430, 75, 23))
        self.start_confirm_button.setStyleSheet("color:rgb(255,255,255)")
        self.start_confirm_button.setObjectName("start_confirm_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 210, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255)")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.trueButton = QtWidgets.QPushButton(self.centralwidget)
        self.trueButton.setGeometry(QtCore.QRect(240, 390, 75, 23))
        self.trueButton.setStyleSheet("color:rgb(255,255,255)")
        self.trueButton.setObjectName("trueButton")
        self.FalseButton = QtWidgets.QPushButton(self.centralwidget)
        self.FalseButton.setGeometry(QtCore.QRect(490, 390, 75, 23))
        self.FalseButton.setStyleSheet("color:rgb(255,255,255)")
        self.FalseButton.setObjectName("FalseButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt; color:#ffffff;\">您已经成功完成练习模块。在主测试中，您将看到一串非汉字的遮挡性字符串，分别在中文词汇的先后持续展200 ms左右。本测试共有12组，点击“开始”进入第一组测试。</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; color:#ffffff;\"><br /></p></body></html>"))
        self.start_confirm_button.setText(_translate("MainWindow", "开始"))
        self.trueButton.setText(_translate("MainWindow", "T"))
        self.FalseButton.setText(_translate("MainWindow", "F"))
